export const GET_IMAGES = 'GET_IMAGES'
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR'

export const GET_IMAGE_BY_ID = 'GET_IMAGE_BY_ID'
export const GET_IMAGE_BY_ID_SUCCESS = 'GET_IMAGE_BY_ID_SUCCESS'
export const GET_IMAGE_BY_ID_ERROR = 'GET_IMAGE_BY_ID_ERROR'
